main-project/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
    path('test/', include('testapp.urls')),
    path('', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    

main-project/news/urls.py
from django.urls import path
from news import views
from django.views.decorators.cache import cache_page

app_name = 'news'
urlpatterns = [
    path('', views.HomeNews.as_view(), name='index-page'),
    # path('', cache_page(60)(views.HomeNews.as_view()), name='index-page'),
    path('category/<int:category_id>/', views.NewsByCategory.as_view(), name='category'),
    path('<int:pk>/', views.ViewNews.as_view(), name='view-news'),
    path('add/', views.CreateNews.as_view(), name='add-news'),
    path('contact/', views.contact, name='contact'),
]

main-project/templates/includs/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'news:index-page' %}">NewsitE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'news:index-page' %}">Додому <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'news:contact' %}">Контактна форма</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'news:add-news' %}">Публікація новини</a>
        </li>
        {% endif %}
      </ul>
      <span class="navbar-text">
        {% if request.user.is_authenticated %}
        Ласкаво просимо, {{ user.username }} | <a href="{% url 'logout' %}">Вийти</a>
        {% else %}
        <a href="{% url 'register' %}">Реєстрація</a> | <a href="{% url 'login' %}">Логін</a>
        {% endif %}
      </span>

    </div>
</nav>

main-project/templates/includs/_sidebar.html
{% load news_tags %}

<div class="list-group">
    {% get_list_categories as categories %}
    {% for item in categories %}
    <a href="{{ item.get_absolute_url }}" class="list-group-item list-group-item-action {% if current_category.id == item.id %}active{% endif %}">{{ item.title }}
    <span class="badge badge-primary badge-pill ml-1"> {{ item.cnt }}</span></a>
    {% endfor %}
    <a href="{% url 'news:index-page' %}" class="list-group-item list-group-item-action">Всі новини</a>
</div>

{% comment "Testing inclusion tags" %}
{% show_categories arg2='User' %}
{% endcomment %}